
-- Settings.lua

-- This file provides settings that may be modified by server admins to customize their plugin
-- It shouldn't be normally necessary to edit this file, but it may be helpful in case of conflicts with other plugins or with a different pre-existing architecture





--- The file from which the galleries and the configuration is read
CONFIG_FILE = "Galleries.cfg";

--- Prefix used in the server console log for messages generated by this plugin
PLUGIN_PREFIX = "Gallery: ";




